require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Leadership::VisitingTeachersController do

  # This should return the minimal set of attributes required to create a valid
  # Leadership::VisitingTeacher. As you add validations to Leadership::VisitingTeacher, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "new_and_returning_member_progress_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Leadership::VisitingTeachersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all leadership_visiting_teachers as @leadership_visiting_teachers" do
      visiting_teacher = Leadership::VisitingTeacher.create! valid_attributes
      get :index, {}, valid_session
      assigns(:leadership_visiting_teachers).should eq([visiting_teacher])
    end
  end

  describe "GET show" do
    it "assigns the requested leadership_visiting_teacher as @leadership_visiting_teacher" do
      visiting_teacher = Leadership::VisitingTeacher.create! valid_attributes
      get :show, {:id => visiting_teacher.to_param}, valid_session
      assigns(:leadership_visiting_teacher).should eq(visiting_teacher)
    end
  end

  describe "GET new" do
    it "assigns a new leadership_visiting_teacher as @leadership_visiting_teacher" do
      get :new, {}, valid_session
      assigns(:leadership_visiting_teacher).should be_a_new(Leadership::VisitingTeacher)
    end
  end

  describe "GET edit" do
    it "assigns the requested leadership_visiting_teacher as @leadership_visiting_teacher" do
      visiting_teacher = Leadership::VisitingTeacher.create! valid_attributes
      get :edit, {:id => visiting_teacher.to_param}, valid_session
      assigns(:leadership_visiting_teacher).should eq(visiting_teacher)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Leadership::VisitingTeacher" do
        expect {
          post :create, {:leadership_visiting_teacher => valid_attributes}, valid_session
        }.to change(Leadership::VisitingTeacher, :count).by(1)
      end

      it "assigns a newly created leadership_visiting_teacher as @leadership_visiting_teacher" do
        post :create, {:leadership_visiting_teacher => valid_attributes}, valid_session
        assigns(:leadership_visiting_teacher).should be_a(Leadership::VisitingTeacher)
        assigns(:leadership_visiting_teacher).should be_persisted
      end

      it "redirects to the created leadership_visiting_teacher" do
        post :create, {:leadership_visiting_teacher => valid_attributes}, valid_session
        response.should redirect_to(Leadership::VisitingTeacher.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved leadership_visiting_teacher as @leadership_visiting_teacher" do
        # Trigger the behavior that occurs when invalid params are submitted
        Leadership::VisitingTeacher.any_instance.stub(:save).and_return(false)
        post :create, {:leadership_visiting_teacher => { "new_and_returning_member_progress_id" => "invalid value" }}, valid_session
        assigns(:leadership_visiting_teacher).should be_a_new(Leadership::VisitingTeacher)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Leadership::VisitingTeacher.any_instance.stub(:save).and_return(false)
        post :create, {:leadership_visiting_teacher => { "new_and_returning_member_progress_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested leadership_visiting_teacher" do
        visiting_teacher = Leadership::VisitingTeacher.create! valid_attributes
        # Assuming there are no other leadership_visiting_teachers in the database, this
        # specifies that the Leadership::VisitingTeacher created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Leadership::VisitingTeacher.any_instance.should_receive(:update_attributes).with({ "new_and_returning_member_progress_id" => "1" })
        put :update, {:id => visiting_teacher.to_param, :leadership_visiting_teacher => { "new_and_returning_member_progress_id" => "1" }}, valid_session
      end

      it "assigns the requested leadership_visiting_teacher as @leadership_visiting_teacher" do
        visiting_teacher = Leadership::VisitingTeacher.create! valid_attributes
        put :update, {:id => visiting_teacher.to_param, :leadership_visiting_teacher => valid_attributes}, valid_session
        assigns(:leadership_visiting_teacher).should eq(visiting_teacher)
      end

      it "redirects to the leadership_visiting_teacher" do
        visiting_teacher = Leadership::VisitingTeacher.create! valid_attributes
        put :update, {:id => visiting_teacher.to_param, :leadership_visiting_teacher => valid_attributes}, valid_session
        response.should redirect_to(visiting_teacher)
      end
    end

    describe "with invalid params" do
      it "assigns the leadership_visiting_teacher as @leadership_visiting_teacher" do
        visiting_teacher = Leadership::VisitingTeacher.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Leadership::VisitingTeacher.any_instance.stub(:save).and_return(false)
        put :update, {:id => visiting_teacher.to_param, :leadership_visiting_teacher => { "new_and_returning_member_progress_id" => "invalid value" }}, valid_session
        assigns(:leadership_visiting_teacher).should eq(visiting_teacher)
      end

      it "re-renders the 'edit' template" do
        visiting_teacher = Leadership::VisitingTeacher.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Leadership::VisitingTeacher.any_instance.stub(:save).and_return(false)
        put :update, {:id => visiting_teacher.to_param, :leadership_visiting_teacher => { "new_and_returning_member_progress_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested leadership_visiting_teacher" do
      visiting_teacher = Leadership::VisitingTeacher.create! valid_attributes
      expect {
        delete :destroy, {:id => visiting_teacher.to_param}, valid_session
      }.to change(Leadership::VisitingTeacher, :count).by(-1)
    end

    it "redirects to the leadership_visiting_teachers list" do
      visiting_teacher = Leadership::VisitingTeacher.create! valid_attributes
      delete :destroy, {:id => visiting_teacher.to_param}, valid_session
      response.should redirect_to(leadership_visiting_teachers_url)
    end
  end

end
