require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NewAndReturningMemberProgressesController do

  # This should return the minimal set of attributes required to create a valid
  # NewAndReturningMemberProgress. As you add validations to NewAndReturningMemberProgress, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "ward_branch" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NewAndReturningMemberProgressesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all new_and_returning_member_progresses as @new_and_returning_member_progresses" do
      new_and_returning_member_progress = NewAndReturningMemberProgress.create! valid_attributes
      get :index, {}, valid_session
      assigns(:new_and_returning_member_progresses).should eq([new_and_returning_member_progress])
    end
  end

  describe "GET show" do
    it "assigns the requested new_and_returning_member_progress as @new_and_returning_member_progress" do
      new_and_returning_member_progress = NewAndReturningMemberProgress.create! valid_attributes
      get :show, {:id => new_and_returning_member_progress.to_param}, valid_session
      assigns(:new_and_returning_member_progress).should eq(new_and_returning_member_progress)
    end
  end

  describe "GET new" do
    it "assigns a new new_and_returning_member_progress as @new_and_returning_member_progress" do
      get :new, {}, valid_session
      assigns(:new_and_returning_member_progress).should be_a_new(NewAndReturningMemberProgress)
    end
  end

  describe "GET edit" do
    it "assigns the requested new_and_returning_member_progress as @new_and_returning_member_progress" do
      new_and_returning_member_progress = NewAndReturningMemberProgress.create! valid_attributes
      get :edit, {:id => new_and_returning_member_progress.to_param}, valid_session
      assigns(:new_and_returning_member_progress).should eq(new_and_returning_member_progress)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new NewAndReturningMemberProgress" do
        expect {
          post :create, {:new_and_returning_member_progress => valid_attributes}, valid_session
        }.to change(NewAndReturningMemberProgress, :count).by(1)
      end

      it "assigns a newly created new_and_returning_member_progress as @new_and_returning_member_progress" do
        post :create, {:new_and_returning_member_progress => valid_attributes}, valid_session
        assigns(:new_and_returning_member_progress).should be_a(NewAndReturningMemberProgress)
        assigns(:new_and_returning_member_progress).should be_persisted
      end

      it "redirects to the created new_and_returning_member_progress" do
        post :create, {:new_and_returning_member_progress => valid_attributes}, valid_session
        response.should redirect_to(NewAndReturningMemberProgress.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved new_and_returning_member_progress as @new_and_returning_member_progress" do
        # Trigger the behavior that occurs when invalid params are submitted
        NewAndReturningMemberProgress.any_instance.stub(:save).and_return(false)
        post :create, {:new_and_returning_member_progress => { "ward_branch" => "invalid value" }}, valid_session
        assigns(:new_and_returning_member_progress).should be_a_new(NewAndReturningMemberProgress)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        NewAndReturningMemberProgress.any_instance.stub(:save).and_return(false)
        post :create, {:new_and_returning_member_progress => { "ward_branch" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested new_and_returning_member_progress" do
        new_and_returning_member_progress = NewAndReturningMemberProgress.create! valid_attributes
        # Assuming there are no other new_and_returning_member_progresses in the database, this
        # specifies that the NewAndReturningMemberProgress created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        NewAndReturningMemberProgress.any_instance.should_receive(:update_attributes).with({ "ward_branch" => "MyString" })
        put :update, {:id => new_and_returning_member_progress.to_param, :new_and_returning_member_progress => { "ward_branch" => "MyString" }}, valid_session
      end

      it "assigns the requested new_and_returning_member_progress as @new_and_returning_member_progress" do
        new_and_returning_member_progress = NewAndReturningMemberProgress.create! valid_attributes
        put :update, {:id => new_and_returning_member_progress.to_param, :new_and_returning_member_progress => valid_attributes}, valid_session
        assigns(:new_and_returning_member_progress).should eq(new_and_returning_member_progress)
      end

      it "redirects to the new_and_returning_member_progress" do
        new_and_returning_member_progress = NewAndReturningMemberProgress.create! valid_attributes
        put :update, {:id => new_and_returning_member_progress.to_param, :new_and_returning_member_progress => valid_attributes}, valid_session
        response.should redirect_to(new_and_returning_member_progress)
      end
    end

    describe "with invalid params" do
      it "assigns the new_and_returning_member_progress as @new_and_returning_member_progress" do
        new_and_returning_member_progress = NewAndReturningMemberProgress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NewAndReturningMemberProgress.any_instance.stub(:save).and_return(false)
        put :update, {:id => new_and_returning_member_progress.to_param, :new_and_returning_member_progress => { "ward_branch" => "invalid value" }}, valid_session
        assigns(:new_and_returning_member_progress).should eq(new_and_returning_member_progress)
      end

      it "re-renders the 'edit' template" do
        new_and_returning_member_progress = NewAndReturningMemberProgress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NewAndReturningMemberProgress.any_instance.stub(:save).and_return(false)
        put :update, {:id => new_and_returning_member_progress.to_param, :new_and_returning_member_progress => { "ward_branch" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested new_and_returning_member_progress" do
      new_and_returning_member_progress = NewAndReturningMemberProgress.create! valid_attributes
      expect {
        delete :destroy, {:id => new_and_returning_member_progress.to_param}, valid_session
      }.to change(NewAndReturningMemberProgress, :count).by(-1)
    end

    it "redirects to the new_and_returning_member_progresses list" do
      new_and_returning_member_progress = NewAndReturningMemberProgress.create! valid_attributes
      delete :destroy, {:id => new_and_returning_member_progress.to_param}, valid_session
      response.should redirect_to(new_and_returning_member_progresses_url)
    end
  end

end
